CREATE DATABASE IF NOT EXISTS rightwice;

USE rightwice;

CREATE TABLE IF NOT EXISTS `user`(
	id BIGINT NOT NULL,
	name VARCHAR(100) NOT NULL,
	login VARCHAR(100) NOT NULL,
	password VARCHAR(100) NOT NULL
);
