CREATE DATABASE IF NOT EXISTS rightwice;

USE rightwice;

CREATE TABLE IF NOT EXISTS `user`(
	id BIGINT NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	login VARCHAR(100) NOT NULL,
	password VARCHAR(100) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS `company`(
	id BIGINT NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	type VARCHAR(100) NOT NULL,
	description VARCHAR(1000) NOT NULL,
	latitude VARCHAR(20) NOT NULL,
	longitude VARCHAR(20) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS `coupon`(
	id BIGINT NOT NULL AUTO_INCREMENT,
	id_company BIGINT NOT NULL,
	name VARCHAR(100) NOT NULL,
	type VARCHAR(100) NOT NULL,
	description VARCHAR(1000) NOT NULL,
	creation_date TIMESTAMP DEFAULT NULL,
	beginning_date TIMESTAMP DEFAULT NULL,
	end_date TIMESTAMP DEFAULT NULL,
	PRIMARY KEY (id)
);
